# Generated by Django 3.2 on 2023-01-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pyscada", "0098_alter_device_polling_interval"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotionEyeServer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(help_text="MotionEye server URL", unique=True)),
                ("admin_username", models.CharField(default="admin", max_length=50)),
                ("admin_password", models.CharField(default="", max_length=50)),
                (
                    "surveillance_username",
                    models.CharField(default="user", max_length=50),
                ),
                ("surveillance_password", models.CharField(default="", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedMotionEyeDevice",
            fields=[],
            options={
                "verbose_name": "MotionEye Device",
                "verbose_name_plural": "MotionEye Devices",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pyscada.device",),
        ),
        migrations.CreateModel(
            name="ExtendedMotionEyeVariable",
            fields=[],
            options={
                "verbose_name": "MotionEye Variable",
                "verbose_name_plural": "MotionEye Variables",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("pyscada.variable",),
        ),
        migrations.CreateModel(
            name="MotionEyeVariable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.PositiveSmallIntegerField(
                        choices=[
                            ("snapshot", "Snapshot"),
                            ("lock", "Lock"),
                            ("unlock", "Unlock"),
                            ("light_on", "Light on"),
                            ("light_off", "Light off"),
                            ("alarm_on", "Alarm on"),
                            ("alarm_off", "Alarm off"),
                            ("up", "Up"),
                            ("right", "Right"),
                            ("down", "Down"),
                            ("left", "Left"),
                            ("zoom_in", "Zoom in"),
                            ("zoom_out", "Zoom out"),
                            ("preset1", "Preset1"),
                            ("preset2", "Preset2"),
                            ("preset3", "Preset3"),
                            ("preset4", "Preset4"),
                            ("preset5", "Preset5"),
                            ("preset6", "Preset6"),
                            ("preset7", "Preset7"),
                            ("preset8", "Preset8"),
                            ("preset9", "Preset9"),
                            ("record_start", "Record start"),
                            ("record_stop", "Record stop"),
                            ("left_text", "Left text overlay"),
                            ("right_text", "Right text overlay"),
                            ("movie_state", "Movie state"),
                            ("device_state", "Device state"),
                            ("recording_mode", "Recording mode"),
                        ],
                        default="snapshot",
                        help_text="Action to send or text overlay to write over the image/video",
                    ),
                ),
                (
                    "motioneye_variable",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pyscada.variable",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MotionEyeDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camera_id",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Camera ID in the MotionEye server"
                    ),
                ),
                (
                    "motioneye_device",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pyscada.device",
                    ),
                ),
                (
                    "motioneye_server",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="motioneye.motioneyeserver",
                    ),
                ),
            ],
        ),
    ]
