# Generated by Django 3.2 on 2023-01-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motioneye', '0002_add_device_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motioneyeserver',
            name='admin_password',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='motioneyeserver',
            name='surveillance_password',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
